# Copyright 2023 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#


[package]
name = "thunder"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
thunder_ripple_sdk = { path = "../thunder_ripple_sdk" }
serde = { version = "1.0", features = ["derive"] }
pact_consumer = {version = "=0.10.4", optional = true}
reqwest = {version = "0.11", optional = true}
expectest = {version = "0.12.0", optional = true}
pact-plugin-driver = {version = "0.4.1", optional = true}
pact_models = {version = "1.0.9", optional = true}
maplit = {version = "1.0.2", optional = true}
test-log = {version = "0.2.11", optional = true}
url = {version = "2.2.2", optional = true}

[features]
contract_tests = ["dep:pact_consumer", "dep:reqwest", "dep:expectest", "dep:pact-plugin-driver", "dep:pact_models", "dep:maplit", "dep:test-log", "dep:url"]
